### ISSUE TITLE
Refactor and Optimize Expense Tracker Code in Easy/expense-tracker/src/App.tsx

### ISSUE THREAD

**Issue by Amansingh0807** [GDG-GTBIT/Hacktoberfest-2024-Webdev#6]
Refactor App.tsx for improved readability, efficiency, and type safety.

 Key changes:
1. Add Type for Expenses: Define a type Expense to ensure type consistency in historyList.
2. Simplify ID Assignment: Remove unnecessary sorting in addExpenseItem, using a more efficient ID assignment.
3. Add null Check in editExpense: Ensure a null check to prevent runtime errors when editing non-existent items.
4. Improve Comments & Naming: Add brief comments to functions and ensure consistent naming.

**Comment by gurssagar** [comment]
@Amansingh0807 Try to fix the issue and merge the pr into the repo for successful contribution. I have assigned the task to you Thanks for figuring out the error and happy contributing.
