### ISSUE TITLE
Fix Inconsistent URLs and Ensure Scroll Reveal CSS Visibility in Easy/Js Portfolio Basic/main.js

### ISSUE THREAD

**Issue by Amansingh0807** [GDG-GTBIT/Hacktoberfest-2024-Webdev#7]
1. Broken URLs in Contact Section:

- The LinkedIn and GitHub URLs in the Contact section are currently missing proper formatting, making them unclickable. Update them to full URLs (e.g., https://linkedin.com/in/Anonymous), ensuring they open in new tabs.

2. Ensure Scroll Reveal Effect is Visible:

- The scroll reveal effect requires the visible class in style.css to provide a clear animation or transition when elements enter the viewport. Add or verify CSS styles for the visible class to enhance the animation.

**Comment by gurssagar** [comment]
@Amansingh0807  Try to fix the issue and merge the pr into the repo for successful contribution. I have assigned the task to you Thanks for figuring out the error and happy conributing.
